refl: 'SR'
file-root: ''
file-specs:
  blues:
    LC08: '{refl}B2.tif'
    LE07: '{refl}B1.tif'
    LT05: '{refl}B1.tif'
    LT04: '{refl}B1.tif'
  greens:
    LC08: '{refl}B3.tif'
    LE07: '{refl}B2.tif'
    LT05: '{refl}B2.tif'
    LT04: '{refl}B2.tif'
  reds:
    LC08: '{refl}B4.tif'
    LE07: '{refl}B3.tif'
    LT05: '{refl}B3.tif'
    LT04: '{refl}B3.tif'
  nirs:
    LC08: '{refl}B5.tif'
    LE07: '{refl}B4.tif'
    LT05: '{refl}B4.tif'
    LT04: '{refl}B4.tif'
  swir1s:
    LC08: '{refl}B6.tif'
    LE07: '{refl}B5.tif'
    LT05: '{refl}B5.tif'
    LT04: '{refl}B5.tif'
  swir2s:
    LC08: '{refl}B7.tif'
    LE07: '{refl}B7.tif'
    LT05: '{refl}B7.tif'
    LT04: '{refl}B7.tif'
  thermals:
    LC08: 'BTB10.tif'
    LE07: 'BTB6.tif'
    LT05: 'BTB6.tif'
    LT04: 'BTB6.tif'
  qas:
    LC08: 'PIXELQA.tif'
    LE07: 'PIXELQA.tif'
    LT05: 'PIXELQA.tif'
    LT04: 'PIXELQA.tif'

conus-extent:
  xmin: -2565585
  ymax: 3314805
  xmax: 2384415
  ymin: 14805
alaska-extent:
  xmin: -851715
  ymax: 2474325
  xmax: 1698285
  ymin: 374325
hawaii-extent:
  xmin: -444345
  ymax: 2168895
  xmax: 305655
  ymin: 1718895

conus-tileaff: [-2565585, 150000, 0 , 3314805, 0, -150000]
conus-chipaff: [-2565585, 3000, 0 , 3314805, 0, -3000]

acquired: '1980-01-01/2015-12-31'
